### PR TITLE
feat: git integration

### LINKED ISSUE #116: Git Integration
We need to implement Git integration within the web IDE to allow users to manage their projects with version control features directly from the IDE interface. This feature will provide users the ability to interact with their Git repositories without leaving the environment.

**Tasks:**
- [ ] Implement Git initialization within the project.
- [ ] Add support for committing changes with commit messages.
- [ ] Implement file staging/unstaging functionality.
- [ ] Add push and pull functionality with proper error handling.
- [ ] Implement Git commit history viewing feature.
- [ ] Basic support for handling merge conflicts within the IDE.
- [ ] Add functionality to clone a repository into the IDE.

### PR DESCRIPTION
**Pull request by rahulyadav-57**
Resolves #116

### CODE REVIEW

**Comment by anton-trunov** [comment]
let's move on with this PR

**Review by verytactical — DISMISSED** [review]
If it works, it works. Let's merge this.

**Comment by rahulyadav-57** [comment]
@verytactical There are some changes required like diff viewer and few improvements. After that we can merge it.

**Review by verytactical — APPROVED** [review]
Let's move on with this PR.

**Pull request merged**
